### ISSUE TITLE
不兼容 node 8.x 版本？

### ISSUE THREAD

**Issue by hirokith** [reactnativecn/node-bsdiff#6]
```
~/dev/github/node-bsdiff(master ✔) tnpm i
✔ Installed 0 packages
✔ Linked 0 latest versions
  CXX(target) Release/obj.target/bsdiff/src/main.o
../src/main.cc:8:10: fatal error: 'cmemory' file not found
#include <cmemory>
         ^~~~~~~~~
1 error generated.
make: *** [Release/obj.target/bsdiff/src/main.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/tnpm/node_modules/_node-gyp@3.6.2@node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/tnpm/node_modules/_npminstall@3.5.0@npminstall/node-gyp-bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dickeylth/dev/github/node-bsdiff
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
✖ Install fail! Error: post install error, please remove node_modules before retry!
Run "sh -c node-gyp rebuild" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "sh -c node-gyp rebuild" error, exit code 1
    at ChildProcess.proc.on.code (/usr/local/lib/node_modules/tnpm/node_modules/_runscript@1.3.0@runscript/index.js:74:21)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
npminstall version: 3.5.0
npminstall args: /usr/local/bin/node /usr/local/lib/node_modules/tnpm/node_modules/_npminstall@3.5.0@npminstall/bin/install.js --tmp=/Users/dickeylth/.tnpm_tmp --no-proxy --disturl=https://tnpm-hz.oss-cn-hangzhou.aliyuncs.com/dist/node --userconfig=/Users/dickeylth/.tnpmrc --registry=http://registry.npm.alibaba-inc.com --china --prefix=/usr/local --forbidden-licenses=AGPL,CPAL,OSL --fix-bug-versions
[tnpm] subprocess:/usr/local/lib/node_modules/tnpm/node_modules/_npminstall@3.5.0@npminstall/bin/install.js exit code: 1, signal: null
[tnpm] mainprocess exit code: 1
```

**Comment by ghost** [comment]
fork 一份，把 cmemory 改成 memory.h
或者直接运行 `npm install swiftneko/node-bsdiff`
